using System;
using System.Collections.Generic;

namespace Data;

internal static class InventoryPayload
{
  // Copy opaque inventory records; never load through Inventory and silently discard unknown items.
  // The native loader still accepts the version-106 records generated by ItemValue.
  internal static byte[]? Get(Dictionary<int, byte[]>? bytes, string? legacy)
  {
    if (bytes != null && bytes.TryGetValue(ZDOVars.s_items, out var current)) return current;
    return string.IsNullOrEmpty(legacy) ? null : Convert.FromBase64String(legacy);
  }

  internal static void Write(ZDO zdo, byte[]? bytes)
  {
    if (bytes == null) return;
    // Snapshot owns its copy, and the destination owns another copy for undo/redo isolation.
    zdo.Set(ZDOVars.s_items, (byte[])bytes.Clone());
    ZDOExtraData.s_strings.Remove(zdo.m_uid, ZDOVars.s_items);
  }
}
